
USER_DOESNT_EXIST = "UDE"
USER_OFFLINE = "UO"
USER_RESTRICTED = "UR"
USER_DECLINED_TUNNEL_REQEUST = "UDTR"
USER_ACCEPTED_TUNNEL_REQEUST = "UATR"

DISCONNECT = "p0"
MAKE_USER_REQUEST = "p1"
DELETE_USER_REQUEST = "p2"
CHANGE_USERNAME_REQUEST = "p3"
LOG_IN_REQUEST = "p4"
LOG_OUT_REQUEST = "p5"
MAKE_RESTRICTED_REQUEST = "p6"
MAKE_UNRESTRICTED_REQUEST = "p7"
MAKE_TUNNEL_REQUEST = "p8"
DECIDE_TUNNEL_CREATION = "p9"

TUNNELED = "p11"

SCREEN_STREAM = "p12"
REMOVE_TUNNEL = "p14"
SCREEN_DATA = "p15"
CODED_TUNNEL = "p16"
RAW_TUNNEL = "p17"

MAKE_USER_REQUEST_RESULT = "r1"
DELETE_USER_REQUEST_RESULT = "r2"
CHANGE_USERNAME_REQUEST_RESULT = "r3"
MAKE_RESTRICTED_REQUEST_RESULT = "r4"
MAKE_UNRESTRICTED_REQUEST_RESULT = "r5"
MAKE_TUNNEL_REQUEST_RESULT = "r6"
DECIDE_TUNNEL_CREATION_RETURN = "r7"




